version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
      - ./grafana.ini:/etc/grafana/grafana.ini:ro  # Mount your custom grafana.ini here
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

  upload_from_influx_to_firestore:
    build: .
    image: upload_data
    depends_on:
      - influxdb


volumes:
  grafana-storage:
  influxdb-storage:
